In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import ops
ops.reset_default_graph()
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
print(sess.run(tf.compat.v1.div(3,4)))
print(sess.run(tf.compat.v1.truediv(3,4)))

Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
0
0.75


In [3]:
print(sess.run(tf.compat.v1.div(3.0,4)))

0.75


In [4]:
print(sess.run(tf.compat.v1.floordiv(3.0,4.0)))

0.0


In [5]:
print(sess.run(tf.compat.v1.mod(22,5)))

2


In [6]:
print(sess.run(tf.compat.v1.mod(22.0,5)))

2.0


In [7]:
print(sess.run(tf.compat.v1.cross([1.,2.,3.],[4.,5.,6.])))

[-3.  6. -3.]


In [8]:
help(tf.compat.v1.cross)

Help on function cross in module tensorflow.python.ops.gen_math_ops:

cross(a, b, name=None)
    Compute the pairwise cross product.
    
    `a` and `b` must be the same shape; they can either be simple 3-element vectors,
    or any shape where the innermost dimension is 3. In the latter case, each pair
    of corresponding 3-element vectors is cross-multiplied independently.
    
    Args:
      a: A `Tensor`. Must be one of the following types: `float32`, `float64`, `int32`, `uint8`, `int16`, `int8`, `int64`, `bfloat16`, `uint16`, `half`, `uint32`, `uint64`.
        A tensor containing 3-element vectors.
      b: A `Tensor`. Must have the same type as `a`.
        Another tensor, of same type and shape as `a`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `a`.



In [9]:
A = tf.fill([3,3],1.0)
B = tf.constant([[-1.,-2.,-3.],[-4.,-5.,-6.],[-7.,-8.,-9.]])
sess.run(tf.compat.v1.abs(B))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [10]:
sess.run(tf.compat.v1.ceil(B))

array([[-1., -2., -3.],
       [-4., -5., -6.],
       [-7., -8., -9.]], dtype=float32)

In [11]:
sess.run(tf.compat.v1.cos(B))

array([[ 0.5403023 , -0.4161468 , -0.9899925 ],
       [-0.6536436 ,  0.28366217,  0.96017027],
       [ 0.75390226, -0.14550003, -0.91113025]], dtype=float32)

In [12]:
C = sess.run(tf.compat.v1.ceil(sess.run(tf.compat.v1.cos(B))))

In [13]:
C

array([[ 1., -0., -0.],
       [-0.,  1.,  1.],
       [ 1., -0., -0.]], dtype=float32)

In [14]:
sess.run(tf.compat.v1.exp(B))

array([[3.6787945e-01, 1.3533528e-01, 4.9787067e-02],
       [1.8315639e-02, 6.7379470e-03, 2.4787523e-03],
       [9.1188197e-04, 3.3546262e-04, 1.2340980e-04]], dtype=float32)

In [15]:
D = sess.run(tf.compat.v1.floor(sess.run(tf.compat.v1.cos(B))))

In [16]:
D

array([[ 0., -1., -1.],
       [-1.,  0.,  0.],
       [ 0., -1., -1.]], dtype=float32)

In [17]:
sess.run(tf.compat.v1.log(A))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [18]:
sess.run(tf.compat.v1.maximum(A,C))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [19]:
sess.run(tf.compat.v1.minimum(A,C))

array([[ 1., -0., -0.],
       [-0.,  1.,  1.],
       [ 1., -0., -0.]], dtype=float32)

In [20]:
sess.run(tf.compat.v1.negative(B))

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [21]:
sess.run(tf.compat.v1.pow(B,2))

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [22]:
sess.run(tf.compat.v1.round(C))

array([[ 1., -0., -0.],
       [-0.,  1.,  1.],
       [ 1., -0., -0.]], dtype=float32)

In [23]:
E = sess.run(tf.compat.v1.rsqrt(tf.compat.v1.exp(B)))
E

array([[ 1.6487212,  2.7182817,  4.481689 ],
       [ 7.3890557, 12.182494 , 20.085537 ],
       [33.11545  , 54.598145 , 90.017136 ]], dtype=float32)

In [24]:
F = sess.run(tf.compat.v1.sqrt(tf.compat.v1.exp(B)))
F

array([[0.60653067, 0.36787942, 0.22313015],
       [0.13533528, 0.082085  , 0.04978707],
       [0.03019738, 0.01831564, 0.011109  ]], dtype=float32)

In [25]:
sess.run(tf.compat.v1.multiply(E,F))

array([[1.        , 0.99999994, 0.99999994],
       [0.99999994, 1.        , 1.        ],
       [1.        , 0.9999998 , 1.        ]], dtype=float32)

In [26]:
sess.run(tf.compat.v1.sign(A))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [27]:
sess.run(tf.compat.v1.sign(B))

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)

In [28]:
sess.run(tf.compat.v1.sign(D))

array([[ 0., -1., -1.],
       [-1.,  0.,  0.],
       [ 0., -1., -1.]], dtype=float32)

In [29]:
help(tf.compat.v1.sign)

Help on function sign in module tensorflow.python.ops.gen_math_ops:

sign(x, name=None)
    Returns an element-wise indication of the sign of a number.
    
    `y = sign(x) = -1` if `x < 0`; 0 if `x == 0`; 1 if `x > 0`.
    
    For complex numbers, `y = sign(x) = x / |x|` if `x != 0`, otherwise `y = 0`.
    
    Example usage:
    >>> tf.math.sign([0., 2., -3.])
    <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.,  1., -1.], dtype=float32)>
    
    Args:
      x: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `int32`, `int64`, `complex64`, `complex128`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `x`.
    
      If `x` is a `SparseTensor`, returns
      `SparseTensor(x.indices, tf.math.sign(x.values, ...), x.dense_shape)`



In [30]:
D

array([[ 0., -1., -1.],
       [-1.,  0.,  0.],
       [ 0., -1., -1.]], dtype=float32)

In [31]:
sess.run(tf.compat.v1.sign(E))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [32]:
E

array([[ 1.6487212,  2.7182817,  4.481689 ],
       [ 7.3890557, 12.182494 , 20.085537 ],
       [33.11545  , 54.598145 , 90.017136 ]], dtype=float32)

In [33]:
sess.run(tf.compat.v1.sin(B))

array([[-0.84147096, -0.9092974 , -0.14112   ],
       [ 0.7568025 ,  0.9589243 ,  0.2794155 ],
       [-0.6569866 , -0.98935825, -0.4121185 ]], dtype=float32)

In [34]:
sess.run(tf.compat.v1.sqrt(A))

array([[0.99999994, 0.99999994, 0.99999994],
       [0.99999994, 0.99999994, 0.99999994],
       [0.99999994, 0.99999994, 1.        ]], dtype=float32)

In [35]:
sess.run(tf.compat.v1.square(B))

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]], dtype=float32)

In [36]:
sess.run(tf.compat.v1.digamma(E))

array([[0.16705728, 0.8049263 , 1.384306  ],
       [1.9308087 , 2.4583962 , 2.9749    ],
       [3.4848251 , 3.9908142 , 4.494435  ]], dtype=float32)

In [37]:
sess.run(tf.compat.v1.erf(B))

array([[-0.8427007, -0.9953223, -0.999978 ],
       [-1.       , -1.       , -1.       ],
       [-1.       , -1.       , -1.       ]], dtype=float32)

In [38]:
sess.run(tf.compat.v1.erfc(B))

array([[1.8427007, 1.9953222, 1.999978 ],
       [2.       , 2.       , 2.       ],
       [2.       , 2.       , 2.       ]], dtype=float32)

In [39]:
help(tf.compat.v1.igamma)

Help on function igamma in module tensorflow.python.ops.gen_math_ops:

igamma(a, x, name=None)
    Compute the lower regularized incomplete Gamma function `P(a, x)`.
    
    The lower regularized incomplete Gamma function is defined as:
    
    
    \\(P(a, x) = gamma(a, x) / Gamma(a) = 1 - Q(a, x)\\)
    
    where
    
    \\(gamma(a, x) = \\int_{0}^{x} t^{a-1} exp(-t) dt\\)
    
    is the lower incomplete Gamma function.
    
    Note, above `Q(a, x)` (`Igammac`) is the upper regularized complete
    Gamma function.
    
    Args:
      a: A `Tensor`. Must be one of the following types: `float32`, `float64`.
      x: A `Tensor`. Must have the same type as `a`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `a`.



In [40]:
sess.run(tf.compat.v1.igamma(A,E))

array([[0.8077043 , 0.93401194, 0.9886857 ],
       [0.999382  , 0.9999949 , 1.        ],
       [1.        , 1.        , 1.        ]], dtype=float32)

In [41]:
sess.run(tf.compat.v1.igammac(A,E))

array([[1.9229566e-01, 6.5988049e-02, 1.1314288e-02],
       [6.1797921e-04, 5.1192928e-06, 1.8921789e-09],
       [4.1508981e-15, 1.9423487e-24, 0.0000000e+00]], dtype=float32)

In [42]:
sess.run(tf.compat.v1.lbeta(E))

array([  -7.5096974,  -40.50966  , -182.8869   ], dtype=float32)

In [43]:
sess.run(tf.compat.v1.lgamma(E))

array([[-1.0544503e-01,  4.4946167e-01,  2.4283466e+00],
       [ 7.3192654e+00,  1.7949518e+01,  3.9594162e+01],
       [ 8.1960083e+01,  1.6271490e+02,  3.1372983e+02]], dtype=float32)

In [44]:
sess.run(tf.compat.v1.squared_difference(A,B))

array([[  4.,   9.,  16.],
       [ 25.,  36.,  49.],
       [ 64.,  81., 100.]], dtype=float32)

In [45]:
from numpy import pi
print(sess.run(tf.compat.v1.div(tf.sin(pi/4.),tf.cos(pi/4.))))

1.0


In [51]:
def custom_polynomial(value):
    return (tf.compat.v1.subtract(3*tf.compat.v1.square(value),value)+10)

In [52]:
print(sess.run(custom_polynomial(11)))

362


In [46]:
!pip install pypandoc

Looking in indexes: http://repo.myhuaweicloud.com/repository/pypi/simple
  Created wheel for pypandoc: filename=pypandoc-1.5-py3-none-any.whl size=21048 sha256=f57f055b4bc40db6448cb20d5f46bb5563751b3c24da110ebe05541f11528266
  Stored in directory: /home/ma-user/.cache/pip/wheels/d2/78/7c/5f9ec5479ee5fc3372eca5a762125cd54abd113c0c0cf79ab6
Successfully built pypandoc
You should consider upgrading via the '/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/bin/python -m pip install --upgrade pip' command.


In [48]:
import pypandoc
output = pypandoc.convert_file('text.md', 'rst').replace("\r", "")
with open("outputfile.rst", "w", encoding="utf8") as f:
    f.write(output)